sudo: required
services:
- docker
before_install:
- docker build -t ciscocloud/mantl-hdfs .
script:
- docker run --rm -it -v $(pwd):/output ciscocloud/mantl-hdfs
deploy:
  provider: bintray
  file: ".bintray"
  user:
    secure: XLZffINSuqcCOEqTdz9B1wOe9lqDIfs5Cbilxb3LprXPZEYsE86MWGUy/kj++amiCK6obkkblpcdLXZGK2khLuI8CUIR+fR1z5fuAKK/qblmXrtuVZTAyc+eUk93tBvRoY8BfM1BdPLRHcAPB6NBT7BYoz/9d0EcghvFsC9OnwXIyJ69JgJheW781JAcJsRuMN/nuTqFTXd2urVImZusmlxzOZlnM549gUZXdLVcwWL5P0Rdq2B32o0BeaQD+vBDMmjjkV9gIMkq5etRrjv+muFAZVFBxxmEbJytlDCUcPJnKRUXOi8Dn4muSWBmEJ2LLpoImESPX13gyDIdhqn+Y5vJn4IeGglij7cq4a7MCPHcWAzyXoWzCnBCGA2nyljBHLLWgPH7sN+7nWNQC04CsndzCkO5v4YUdmnUBM61ymYHgTonnJygfuklGxyCykEC3i0DfW6OdmTZh2p4MZ+WJ3Jq4EBakneBBFF3F36AWr+c8bAxmMQik0lRKfvFuuKiUdaex+jzpmU//BKG7HEn5+o7aMvzFxPkVEPbSJB5CXha4RiO8NELzvZTlyo36tdUC0lS0TXV5qJU+5AJn8U/gSMX0Ps0eo0Oki0zfvKAshq18bpIm0hQHGdySyIVIYibLUe8RSju9Pvf0nCDMLYjPkZrmqJ1kx6QkEKe+DJ4Gxw=
  key:
    secure: Np0SNKU7XL96Wzbkw1PdYbwfjRbik2xPchJH29fOeKgeel+XdJ6R5U2UOztWnZrOGX+flZYVygIJnHKP51m4SGHU3JwmYiYqy4BZhDbeGltjGb1yCo6R6KwANV6vBWLJXwdxAJR6w90kCFMdRuVvwnYAUAaeZi2U+ncSSPxGc03ztVNuyhCLki9X9QPrWX4RVDewfHkdRYWmXn3+SIpUz1EVtCzyaU9R+zPrubaRaYbBdBRUuEOBVIEw8JZiSzv5V6464OGwfsOv1gsco6TrgNUZ+KegK/fUHlyrIi8tjL7Nc+agyEh1jnoXXMSCLiaUxE0bl4WQn5VQItf0ytjGi9USwufpW/hdK2R1UkbdAgwbEg715MtvtFFd4a97MB9qn+mQgupZLwmbthPTy0yJnJfdWE/SCsD9AGRgPjcL2vealAKWvCkK6Lv3FI8rPTt6wPuGj4qvx2fn6jff+nJCc2fJgkYpu+h5zX4TuIrWMtdWghCTqXeJiG0HuNtOHNrUpbu73Pe5aAq5LXYVo3gDSI7QRHKOoWL3qQyxOxsJuDqjsRMzqiqvLIAh26MCn7FEsovQbuzlF7/Q3RMp7npbjWYWonA6v+Ja6lCasb+7FoIWCsvAi2JzY2HISOCXxyTGltN2b/MKXw0LwY7tFo7SjFFauYs9M/asknWNurVSLB0=
  on:
    all_branches: true
  dry-run: false